### ISSUE TITLE
Istanbul hard-fork meta

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#19919]
Accepted EIPs:

 - [x] [EIP-152](https://github.com/ethereum/EIPs/pull/2129): Blake2 compression function F precompile (https://github.com/ethereum/go-ethereum/pull/19972)
 - [x] [EIP-1108](https://eips.ethereum.org/EIPS/eip-1108): Reduce alt_bn128 precompile gas costs (https://github.com/ethereum/go-ethereum/pull/19904)
 - [x] [EIP-1344](https://eips.ethereum.org/EIPS/eip-1344): ChainID opcode (https://github.com/ethereum/go-ethereum/pull/19921)
 - [x] [EIP-1884](https://eips.ethereum.org/EIPS/eip-1884): Repricing for trie-size-dependent opcodes (https://github.com/ethereum/go-ethereum/pull/19743)
 - [x] [EIP-2028](https://eips.ethereum.org/EIPS/eip-2028): Calldata gas cost reduction (https://github.com/ethereum/go-ethereum/pull/19931)
 - [x] [EIP-2200](https://github.com/ethereum/EIPs/pull/2200): Rebalance net-metered SSTORE gas cost (https://github.com/ethereum/go-ethereum/pull/19964)

Maintenance stuff:

 - [x] Define the Istanbul fork chain config (https://github.com/ethereum/go-ethereum/pull/19904)
 - [x] Integrate Istanbul meta fork config with individual EIPs (https://github.com/ethereum/go-ethereum/pull/19993)
 - [x] Define `--istanbul.override` flag to support last minute delay (https://github.com/ethereum/go-ethereum/pull/20004)
 - [ ] Integrate Istanbul into Puppeth
   - https://github.com/ethereum/go-ethereum/pull/19926 - need the chain specs for Parity, need to finalize everything before letting people enable it

**Comment by holiman** [comment]
Re blake, see https://github.com/keep-network/go-ethereum/pull/4

**Comment by rjl493456442** [comment]
The implementation for calldata EIP can be found https://github.com/liorgold2/go-ethereum/pull/1

**Comment by holiman** [comment]
Re "sane limits"
> As far as I see it based on the discussions in https://ethereum-magicians.org/t/eip-1985-sane-limits-for-certain-evm-parameters/3224, all the proposed "limits" are already practical invariants of the system. I'm not sure what this EIP is supposed to "do" in Istanbul.

The only thing that actually makes a difference, is that it would make the following invalid:
- A block which has an `uncle`, where the `uncle.timestamp` does not fit within `int32`. 

We need to coordinate on that change, otherwise there's a window of attackability by malicious miner. If we do that, and nobody "exploits" until then (which would be meaningless), then we can later post-facto declare "It has always been thus".

**Comment by MariusVanDerWijden** [comment]
I think this can be closed now, as istanbul is long merged
