### ISSUE TITLE
website/docs: documentation TODO list

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#19989]
### Installation guides

  - [x] Linux
  - [x] MacOS
  - [x] Windows
  - [x] Docker

### Using Geth

  - [ ] Sync Modes (write new page)
  - [x] Mining (migrate old wiki page)
  - [x] RPC API (how to enable, configure HTTP/WS/IPC, link to RPC spec)
  - [x] RPC Subscriptions (migrate wiki page)
  - [x] Admin RPC methods (migrate wiki page)
  - [ ] Chain tracing RPC methods (migrate wiki page)
  - [ ] GraphQL (write new page)
  - [x] Account management (migrate wiki page)
  - [x] Console (migrate wiki page)
  - [ ] Config File (write new page)

### Developing with Geth

  - [x] Dev Mode
  - [x] Private Network
  - [ ] Puppeth (write new page)
  - [x] Clique RPC API (write new page)

### Developing Geth itself

   - [x] Dev Guide (migrate wiki page)
   - [x] Code Review Guideline (migrate page)
   - [x] Issue and PR Workflow (write new page)
   - [ ] Join the Geth (write new page)

### Clef
   - [x] API Docs
   - [x] Configuration / Rules
   - [ ] User Interface

**Comment by ChrisChinchilla** [comment]
Started in #20016 covering some of these points, I'll break out more tasks soon.

**Comment by ChrisChinchilla** [comment]
Currently working on dev mode and private networks, questions to follow…

**Comment by fjl** [comment]
#20229 puts this basic structure in place and resolves most of the missing items in the list

**Comment by ChrisChinchilla** [comment]
Private network in the context of a local cluster is here https://github.com/ethereum/go-ethereum/pull/20256 but also needs more detail on other options present in current docs.

**Comment by ChrisChinchilla** [comment]
While I wait for reviews on that, I am going to take sync modes next

**Comment by zjiekai** [comment]
I find the [back & restore](https://github.com/ethereum/go-ethereum/wiki/Backup-&-restore) wiki page useful.  Will it be in the doc?

**Comment by fjl** [comment]
Would be nice to have that one.

**Comment by ChrisChinchilla** [comment]
I think bringing back some of the wiki pages was always part  of the plan. @zjiekai feel free to make a PR, you might get to it quicker than us. Probably in the "using geth" section?

**Comment by zjiekai** [comment]
@ChrisChinchilla Would a simple copy & paste PR suffice? I'm not native in English.

**Comment by ChrisChinchilla** [comment]
@zjiekai Yup, and then I can polish it from there.

**Comment by zjiekai** [comment]
Oh, I see. "Back and restore" is already in the doc. Sorry... 

<https://geth.ethereum.org/docs/install-and-build/backup-restore>

**Comment by PolkovnikFSB** [comment]
> ### Installation guides
> * [x]  Linux
> * [x]  MacOS
> * [x]  Windows
> * [x]  Docker
> 
> ### Using Geth
> * [ ]  Sync Modes (write new page)
> * [x]  Mining (migrate old wiki page)
> * [x]  RPC API (how to enable, configure HTTP/WS/IPC, link to RPC spec)
> * [x]  RPC Subscriptions (migrate wiki page)
> * [x]  Admin RPC methods (migrate wiki page)
> * [ ]  Chain tracing RPC methods (migrate wiki page)
> * [ ]  GraphQL (write new page)
> * [x]  Account management (migrate wiki page)
> * [x]  Console (migrate wiki page)
> * [ ]  Config File (write new page)
> 
> ### Developing with Geth
> * [x]  Dev Mode
> * [x]  Private Network
> * [ ]  Puppeth (write new page)
> * [x]  Clique RPC API (write new page)
> 
> ### Developing Geth itself
> * [x]  Dev Guide (migrate wiki page)
> * [x]  Code Review Guideline (migrate page)
> * [x]  Issue and PR Workflow (write new page)
> * [ ]  Join the Geth (write new page)
> 
> ### Clef
> * [x]  API Docs
> * [x]  Configuration / Rules
> * [ ]  User Interface

**Comment by PolkovnikFSB** [comment]
#0x5A0b54D5dc17e0AadC383d2db43B0a0D3E029c4c

**Comment by MariusVanDerWijden** [comment]
closed in favor of https://github.com/ethereum/go-ethereum/issues/20260
