### ISSUE TITLE
Berlin hard-fork meta

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#19994]
Probably Berlin:

 - [ ] [EIP-1057](https://eips.ethereum.org/EIPS/eip-1057): ProgPoW, a Programmatic Proof-of-Work
   - https://github.com/ethereum/go-ethereum/pull/17731 - needs final version update, needs review
 - [ ] [EIP-1962](https://eips.ethereum.org/EIPS/eip-1962): EC arithmetic and pairings with runtime definitions

Tentative Berlin:
- [ ] [EIP-1702](https://eips.ethereum.org/EIPS/eip-1702): Generalized account versioning scheme
   - https://github.com/ethereum/go-ethereum/pull/19826 - done, needs review
   - I don't want to introduce flexibility that we don't even know what to use for or if it's even warranted. All I see in it is an escape hatch on how to hack on features without caring about backward compatibility. We need a very very good reason to warrant the huge maintenance overhead of 2 EVM versions in the same codebase.
- [ ] [EIP-663](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-663.md): Unlimited SWAP and DUP
  - There are issues with all proposed variants. See https://ethereum-magicians.org/t/eip-663-unlimited-swap-and-dup-instructions/3346 for details.
- [ ] [EIP 1380](http://eips.ethereum.org/EIPS/eip-1380): Reduced gas cost for call to self
  - Are we sure there are no possible DoS vectors that all of a sudden get reenabled? https://ethereum-magicians.org/t/eip-1380-reduced-gas-cost-for-call-to-self/1242
 - [ ] [EIP 1985](http://eips.ethereum.org/EIPS/eip-1985): Sane limits for certain EVM parameters
   - As far as I see it based on the discussions in https://ethereum-magicians.org/t/eip-1985-sane-limits-for-certain-evm-parameters/3224, all the proposed "limits" are already practical invariants of the system. I'm not sure what this EIP is supposed to "do" in Istanbul.
 - [ ] [EIP 2045](http://eips.ethereum.org/EIPS/eip-2045): Particle gas costs for EVM opcodes
   - This doesn't seem like a trivial change added last minute. I can imagine there are corner cases around OOG calculations because they all of a sudden need to take into account +1 from the particles (maybe we can work around by adding +1 immediately when the particles are touched instead of tracking them at all). Gas calculation overflows may or may not be affected. The discussion thread https://ethereum-magicians.org/t/eip-2045-particle-gas-costs/3311 debates whether to do with account versions or not (would be very messy to have 2 gas calculation pathways imho and also why would we keep old contracts suboptimal), whether to use 10K or 1K or 1M units as particles. Why it this considered with so many open questions?
 - [ ] [EIP 2046](http://eips.ethereum.org/EIPS/eip-2046): Reduced gas cost for static calls made to precompiles
   - The EIP seems to reference [EIP-1352](https://eips.ethereum.org/EIPS/eip-1352) as it's base, which was dropped from Istanbul. As such, this EIP is open to interpretation. Without a hard fast clarification, I don't see why this would make Istanbul.

**Comment by ytrezq** [comment]
@karalabe : so ᴇɪᴘ‑1702 was withdrawn from Istambul… Why ?

**Comment by karalabe** [comment]
Closing as it hasn't been maintained.
