### ISSUE TITLE
Most frequent build failures

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20699]
Here are the test cases that failed most frequently in the last 250 builds on master (most frequent first). The list was generated by https://github.com/adamschmideg/ethereum/tree/master/travis

- [x] [TestSendTransactions63, eth](https://github.com/ethereum/go-ethereum/issues/20725): #20234
- [x] TestSendTransactions64, eth: #20234
- [x] [TestCheckpointChallenge, eth](https://github.com/ethereum/go-ethereum/issues/20726): #20741
- [x] TestSendTransactions65, eth: #20234
- [x] TestClientCancelIPC, rpc - @fjl: maybe fixed by #20752
- [x] TestClientCancelWebsocket, rpc - @fjl: maybe fixed by #20752 
- [x] TestBroadcastBlock, eth, maybe fixed by #20699
- [x] TestTimerFunc, metrics, maybe fixed by #20818
- [ ] [TestBoundedHeavyForkedSync63Fast](https://github.com/ethereum/go-ethereum/issues/20842), eth/downloader
- [x] TestGenerateBlockAndImportEthash, miner: #20698
- [ ] TestHTTPNetwork, p2p/simulations fails [here](https://github.com/ethereum/go-ethereum/blob/master/p2p/simulations/http_test.go#L335) - @fjl 
- [x] TestSimulation, whisper/whisperv6 [fails here](https://github.com/ethereum/go-ethereum/blob/master/whisper/whisperv6/peer_test.go#L287) and [here with `bind: address already in use`](https://github.com/ethereum/go-ethereum/blob/master/whisper/whisperv6/peer_test.go#L230) @gballet -> disabled
- [ ] TestBoundedForkedSync63Fast, eth/downloader
- [ ] TestWSAttachWelcome, cmd/geth @rjl493456442 
- [ ] TestHTTPAttachWelcome, cmd/geth @rjl493456442 
- [ ] TestBoundedForkedSync64Fast, eth/downloader
- [x] TestOdrContractCallLes2, les: #20741
- [x] TestGolangBindings, abi/bind: #20698
- [ ] TestBoundedHeavyForkedSync64Fast, eth/downloader
- [x] TestOdrTxStatusLes3, les: #20741

**Comment by adamschmideg** [comment]
See also the table of failing tests in https://github.com/adamschmideg/ethereum/blob/master/travis/Visualize.ipynb

**Comment by rjl493456442** [comment]
For `TestHandshake` I can't repro locally after running 11173 times.

**Comment by adamschmideg** [comment]
First fix #20814

**Comment by holiman** [comment]
See https://github.com/ethereum/go-ethereum/pull/20818 
and https://github.com/ethereum/go-ethereum/pull/20815

**Comment by holiman** [comment]
See https://github.com/ethereum/go-ethereum/pull/20860

**Comment by adamschmideg** [comment]
Some have been resolved, some opened as individual issues as [flaky tests](https://github.com/ethereum/go-ethereum/issues?q=is%3Aissue+is%3Aopen+flaky+on+travis)
