### ISSUE TITLE
PoC9 changes to P2P

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#240]
PoC 8 (E.T.A mid Feburary) introduces RLPX, a new encrypted, authenticated and properly framed transport protocol for the P2P layer.

The current revision of the RLPX specification [is here](https://github.com/ethereum/devp2p/blob/master/rlpx.md).

The PoC 8 document [is on etherpad](https://ethereum.etherpad.mozilla.org/19).

**The changes are**

- [x] ~~New framing layer that ensures fair queueing among protocols~~ (not in PoC 8)
- [x] ~~transport encryption~~ (very likely not in PoC8)
- [x] Kademlia-like node table (@fjl #275)
- [x] Encryption handshake (@zelig #271)
- [x] Integration of the above into package p2p (@fjl #292)

**Tasks beyond basic implementation**

- [x] [CLI flags for system-testing](https://github.com/ethereum/system-testing/issues/30)
  - [x] -bootnodes
  - [x] -nodekey
- [x] Port mapping integration for `p2p/discover`
- [x] A replacement for `cmd/peerserver` that can be used as Kademlia bootstrap node
- [x] Make UDP tests in package `p2p/discover` more reliable
- [x] Improve network UI in Mist

**Remaining Tasks for PoC9**
- [x] Fix `Table.closest` so it doesn't send duplicates (use random bumps in the tests)
- [x] Persist discovery nodes for faster network join (being worked on by @karalabe, #793).

**Comment by obscuren** [comment]
@felix please update

**Comment by fjl** [comment]
updated. will update more often.

**Comment by fjl** [comment]
We now have a basic version that implements the features above.
The merge into develop will need coordination among implementations because
of its effect on the test network.

- cpp-ethereum isn't ready yet.
- pyethereum might be ready, will ask @heikoheiko.
- on our side, there are a few bugs that I know of, e.g. #227.

I will work on ironing out bugs for now.

**Comment by fjl** [comment]
Added some more tasks.

**Comment by fjl** [comment]
done
