### ISSUE TITLE
Git get

### ISSUE THREAD

**Issue by Fernando07654328664** [ethereum/go-ethereum#27709]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/go-ethereum/pull/27708
- [ ] https://github.com/ethereum/go-ethereum/pull/27527
- [ ] https://github.com/ethereum/go-ethereum/pull/27702
- [ ] https://github.com/ethereum/go-ethereum/pull/27705
- [ ] https://github.com/ethereum/go-ethereum/pull/27629
- [ ] https://github.com/ethereum/go-ethereum/pull/27700
- [ ] https://github.com/ethereum/go-ethereum/pull/25662
```

**Comment by Fernando07654328664** [comment]
Get suport
