### ISSUE TITLE
# másolata

### ISSUE THREAD

**Issue by Krizsakne** [ethereum/go-ethereum#28803]
# másolata

_Originally posted by @Krizsakne in https://github.com/ethereum/kzg-ceremony/issues/138#issuecomment-1890398804_
            
```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/go-ethereum/pull/28775
- [ ] https://github.com/ethereum/go-ethereum/issues/21774
- [x] Hi
- [x] Hih8
- [ ] https://github.com/ethereum/go-ethereum/pull/26116
- [ ] https://github.com/ethereum/go-ethereum/issues/28805
- [ ] https://github.com/ethereum/go-ethereum/issues/28806
```

**Comment by Krizsakne** [comment]
https://github.com/ethereum/go-ethereum/issues/28803#issue-2080345890

**Comment by cecuabin** [comment]
M^-indmg3/2t^2^-1/2g8 -dmu'cl^2 = -R^2 . 3dR3^3/4^^4/3 +dt5/AKPR arcos +1/2mFU(uv) +-b^-79/2dtsh*.dmb
RRF = L^n!.Ad8D + d9DVmu^ngc445301 m/s^-2/1(spi)hz:=.rsc
-sh^2/g161^KPR22sh^1/2 = Rpwi + w1t1 - dt -dttppvo*.int

**Comment by Krizsakne** [comment]
Helll9

**Comment by Krizsakne** [comment]
> M^-indmg3/2t^2^-1/2g8 -dmu'cl^2 = -R^2. 3dR3^3/4^^4/3 +dt5/AKPR arcos +1/2mFU(uv) +-b^-79/2dtsh*.dmb RRF = L^n!.Ad8D + d9DVmu^ngc445301 m/s^- 2/1(spi)hz:=.rsc -sh^2/g161^KPR22sh^1/2 = Rpwi + w1t1 - dt -dttppvo*.int

**Comment by Krizsakne** [comment]
I8000 hi
