### ISSUE TITLE
Helll9

### ISSUE THREAD

**Issue by Krizsakne** [ethereum/go-ethereum#28807]
Helll9

_Originally posted by @Krizsakne in https://github.com/ethereum/go-ethereum/issues/28803#issuecomment-1890831796_
            
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/go-ethereum/issues/28806
- [ ] https://github.com/ethereum/go-ethereum/pull/26116
- [ ] https://github.com/ethereum/go-ethereum/issues/28803
- [ ] https://github.com/ethereum/go-ethereum/issues/21774
- [ ] https://github.com/ethereum/go-ethereum/issues/28805
- [ ] https://github.com/ethereum/go-ethereum/pull/28804
- [ ] https://github.com/ethereum/go-ethereum/pull/28784
- [ ] https://github.com/ethereum/go-ethereum/pull/28787
- [ ] https://github.com/ethereum/go-ethereum/pull/28792
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/go-ethereum/issues/28806
- [ ] https://github.com/ethereum/go-ethereum/pull/28804
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/go-ethereum/issues/28803
- [ ] https://github.com/ethereum/go-ethereum/pull/26116
```
