### ISSUE TITLE
> M^-indmg3/2t^2^-1/2g8 -dmu'cl^2 = -R^2. 3dR3^3/4^^4/3 +dt5/AKPR arcos +1/2mFU(uv) +-b^-79/2dtsh*.dmb RRF = L^n!.Ad8D + d9DVmu^ngc445301 m/s^- 2/1(spi)hz:=.rsc -sh^2/g161^KPR22sh^1/2 = Rpwi + w1t1 - dt -dttppvo*.int

### ISSUE THREAD

**Issue by Krizsakne** [ethereum/go-ethereum#28808]
> M^-indmg3/2t^2^-1/2g8 -dmu'cl^2 = -R^2. 3dR3^3/4^^4/3 +dt5/AKPR arcos +1/2mFU(uv) +-b^-79/2dtsh*.dmb RRF = L^n!.Ad8D + d9DVmu^ngc445301 m/s^- 2/1(spi)hz:=.rsc -sh^2/g161^KPR22sh^1/2 = Rpwi + w1t1 - dt -dttppvo*.int

_Originally posted by @Krizsakne in https://github.com/ethereum/go-ethereum/issues/28803#issuecomment-1890838331_
            
```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/go-ethereum/issues/28803
- [ ] https://github.com/ethereum/go-ethereum/pull/28804
- [ ] https://github.com/ethereum/go-ethereum/issues/28807
- [ ] https://github.com/ethereum/go-ethereum/issues/28806
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/go-ethereum/issues/28807
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/go-ethereum/issues/28803
- [ ] https://github.com/ethereum/go-ethereum/pull/26116
- [ ] https://github.com/ethereum/go-ethereum/pull/28775
- [ ] https://github.com/ethereum/go-ethereum/pull/28802
```

**Comment by fjl** [comment]
Question regarding the timeout: Can I disable this? I'm running large queries and get error messages like this:

requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(1197 bytes read, 851 more expected)', IncompleteRead(1197 bytes read, 851 more expected))
I tried several approaches with requests, httpx to talk to the graphql on geth.
Connected straight to the port as well as routing it through nginx. Seems geth is just chopping off data transfer.

Ideally you'd want to run a setup with a proper firewall config, and nginx or another webserver handling and limiting the traffic and timeouts for connections instead of exposing geth RPC / WSS directly to the internet. Hoping there's a parameter, read a through the issues here and the docs. Can't really figure out how to disable this.
