### ISSUE TITLE
Etherum

### ISSUE THREAD

**Issue by Krizsakne** [ethereum/go-ethereum#28809]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/go-ethereum/issues/28808
- [ ] https://github.com/ethereum/go-ethereum/pull/28804
- [ ] https://github.com/ethereum/go-ethereum/issues/28803
- [ ] https://github.com/ethereum/go-ethereum/pull/26116
- [ ] https://github.com/ethereum/go-ethereum/pull/28775
- [ ] https://github.com/ethereum/go-ethereum/issues/21774
```
