### ISSUE TITLE
-----BEGIN PGP SIGNATURE-----

### ISSUE THREAD

**Issue by boy1bot2** [ethereum/go-ethereum#29454]
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCgAGBQJW4aZxAAoJELteLjW5Ljc+KEcP/RVSkj+dWnjIalN0cofdq98M
+BqJ5VYP3L/pp//SJiX4RM0E87WaQKK4TpwefaTnf3vYISDqsVwAWyLXUnAGOgjy
STbW/nhc1HRx+s9ayvqKuRrCItVhqZfmqhWpxGIq5xZSn5tBNaW0Kod3z/W7WT6z
O1bgC9f+7lf1b9QiCvdpX3o5KCxKDz+L6mSZhlGPXR1mqbD9Ugucv0H8w+Vb6pZg
uVs5v+5icV0wrkCx2nmSq15xv21Hz05GY4AJVpMuRqPgtcQ0j62VSGPzYDIyn1K6
hr7xByUv2r44WgP3fJqwxYlJkwdL6cQBaqMQp1UDt51xO5Ahaf/hF6oNkFrvhIAe
zelBolWS5YiyA6o/X0A46ma5tRNtsLmQfnXtzx3Ww9bIuvQBbWlveTPWsSgb051X
411Vt/pVd6R8q3yBB0umhAJG9qyZPM1o8UouLESI+6wjYi0TElfhi9bFD7Unm3sU
99x/Hb7oGPK8oWNbJSVBi5GIEjxeWwNPPAwBZI6GwYLqYQNlhJ+OHWCLXc/M4FvW
ObkMCHDoAqxmAjsfRM3nm+yvSwLOsNP1s4HmU91BektaPzJ4i/V0j+DV8gtRlagK
gEKiXsci9a/T8dkeNRoR8+SguErxIOneeeHOcuM8faIFKlFDv1Vg4XCTH0mN8CV0
PU4MWVh2bd7q1L4+Wxzy
=Dx4p
-----END PGP SIGNATURE-----
`

> 0xc1d78db0f5d00110935df8679a9b61da759f1e04

 `

_Originally posted by @boy1bot2 in https://github.com/ethereum/go-ethereum/issues/21539#issuecomment-2038624900_
            
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/go-ethereum/issues/27539
- [ ] https://github.com/ethereum/go-ethereum/issues/29404
- [ ] https://github.com/ethereum/go-ethereum/issues/29456
- [x] https://github.com/ethereum/go-ethereum/issues/29455
```
