### ISSUE TITLE
swarm network rewrite

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#2960]
This issue lists the subtasks for the grand swarm network rewrite for POC 0.4
- [x] standard protocol p2p protocol abstraction  https://github.com/ethereum/go-ethereum/pull/2959
  - [x] bzz info for peers info  API https://github.com/ethereum/go-ethereum/issues/2042
- [x] hive  integration and peer comms rewrite 
  - [x] new kademlia using POT
  - [x] https://github.com/ethereum/go-ethereum/issues/2044
  - [ ] https://github.com/ethereum/go-ethereum/issues/2766
  - [ ] ~https://github.com/ethereum/go-ethereum/issues/2060~
  - [ ] ~https://github.com/ethereum/go-ethereum/issues/2765~
  - [ ] ~https://github.com/ethereum/go-ethereum/issues/2254~
- [ ] sync channels (syncer rewrite)
- [ ] syncdb, netstore and syncer backend rewrite based on new db index scheme 
  - [ ] cached deliveries do not enter syncdb https://github.com/ethereum/go-ethereum/issues/2046
  - [ ] push on delete from disc https://github.com/ethereum/go-ethereum/issues/2045
  - [x] unbounded parallelisation memory issues https://github.com/ethereum/go-ethereum/issues/2641
- [ ] swap rewrite
- [ ] request handler - depo/forwarder rewrite
- [x] pss backbone
