### ISSUE TITLE
ABIGEN v2 tracking issue

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#30701]
This issue is about finishing the work to ship ABIGEN v2. The prototype of it is in this pull request: #26782.

To get it ready we need:

- [x] Rebase #26782 branch on master
- [x] Move the v2 stuff to its own package. Use accounts/abi/bind2 for now. Final package name TBD.
  - note this will require duplicating some stuff from accounts/abi/bind into the new package
- [x] Adding tests. To test this, we should create an example contract binding and run all functions of bind2 against a simulated backend
  - [x] transact
  - [x] call
  - [x] log filtering
  - [x] log watching
- [x] Code generation tests. These should just compare the generated code to a known output.
- [x] Adding function GoDoc comments and examples
- [x] Creating documentation page on geth.ethereum.org
