### ISSUE TITLE
swarm binary merkle hash over 32-byte segments with segment proofs

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#3451]
binary merkle hash over 32-byte segments for swarm chunk hash 
this will replace simple sha3 over chunks 

* [x] spec for the hash and offset-based proofs
* [x] implement binary hash, see https://github.com/ethersphere/go-ethereum/pull/48
* [ ] provide offset-based segment proofs

**Comment by orenyodfat** [comment]
**phase 1 :** 
 - BMTHash + hash.Hash interface.
 - Replace "sha3" at pyramid and tree chunker with BMTHash.  
**phase 2:** 
 -API to get an inclusion proof for a given index in the tree.
 -API to Check a proof against a valid BMTHash root.
**phase 3:**
- have proofs for any offset and length requiring potentially several proofs 
**phase 4:**
-should include the proof of custody salted hash (see the crash /smash orange paper)
**phase 5:**
-should implement the verification in solidity inline assembly
for the blockchain

**Comment by zelig** [comment]
https://github.com/ethereum/go-ethereum/pull/14334

**Comment by zelig** [comment]
superceded by https://github.com/ethereum/go-ethereum/issues/14962
