### ISSUE TITLE
SEC-13 Parent issue for all uncle validation / logic security issues

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#415]
- [x] Fix is-kin property: https://github.com/ethereum/go-ethereum/issues/387
- [x] Ensure uncle header validation: https://github.com/ethereum/go-ethereum/issues/381
- [x] Ensure uncle uniqueness (a block cannot be uncle more than one time)

**Comment by Gustav-Simonsson** [comment]
Re-opening since we still do not have working block (chain) tests for this.
