### ISSUE TITLE
SEC-24 Parent issue for ethash / PoW security issues

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/go-ethereum#499]
- [x] Currently if DAG becomes unreadable user needs to manually remove the file before the miner works. Ensure the file is automatically repaired / re-created in case the file is corrupted.
- [x] If DAG size grows larger than the C.int max size overflow occurs and DAG is only partly written to file. Ensure DAG is written in chunks smaller than C.int max size.
- [x] Switch order of pow.dagMutex.Lock(), pow.cacheMutex.Lock() and deferred unlocks to avoid potential deadlocks.
- [x] Validate DAG file after reading it before it's searched, otherwise segfault can happen in cgo which brings down the Go client.
- [x] Change DAG location from /tmp directory to the ethereum DATADIR. This avoids DAG file being cleared at reboots and also avoids issues with file permissions as /tmp is globally write-able. 
- [x] Verify DAG memory allocation. E.g., it seems Go needs more available memory than the size of the memory to-be-allocated. Consider putting the DAG memory handling in the C lib for better predictability of system RAM requirements as the DAG file grows at every epoch.

**Comment by obscuren** [comment]
Issue should be closed as soon as we have moved file handling to the `ethash` C code.
