### ISSUE TITLE
Additional CLI account commands

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#541]
- [x] support non-interactive password input #550
- [x] `ethereum account import <key>` #550
- [x] `wallet import` for ether presale wallet import #550
- [x] settable etherbase #580

https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts

**Comment by zelig** [comment]
how about 

`ethereum account export <address> <path>`
and 
`ethereum account import <keyfilepath>`
i would not encourage people to have their private keys in console histories.

**Comment by fjl** [comment]
Importing from command line is important for system-testing. Maybe both should be supported.

**Comment by zelig** [comment]
I think you can always get round it ;)

    ethereum account import <(echo mynotsosecrettestkey)

**Comment by obscuren** [comment]
I've never seen the importance of supplying a file when you can do <backtick>cat file<backtick> (apperantly iPhones haven't got backticks on their keyboard)

**Comment by tgerring** [comment]
Tap and hold the single quote key--a popover menu should appear with the backpack symbol ;)

**Comment by zelig** [comment]
@obscuren sure you can get round both ways. 
Right, how about the best of both worlds: allow filepath only and fall back to stdin if arg missing.
Both passwords and keys . This  implements the design principle that the less secure a solution, the more hackery it requires.

Scenarios:

naive user:

      ethereum account import
      please enter your private key:
      please enter a passphrase:
      Remember your passphrase!
      Oh, and dont forget your passphrase!

geek scripting in public cafe or peeps copy/pasting instructions on stackoverflow:

      ethereum --passwd /path/to/passfile account import path/to/.ethkey.prv >  /dev/null 2>&1

tester:

     ethereum --passwd <(echo 'youcanhackme') account import <(echo '34aebf5689fed6....')

or 

    ethereum account --unencrypted-keys import <(echo '34aebf5689fed6....')

The same for `--unlock` and `export` btw

**Comment by obscuren** [comment]
@zelig I think you misunderstand me.

```
ethereum --import `cat myFile`      # note this doesn't output anything from cat
```

Is the same as doing (without the need to actually code it up yourself)

```
ethereum --import-file myFile
```

Or does that have any other implications?

@tgerring Oh, thanks :-)

**Comment by fjl** [comment]
argv can be read by anyone, input can't.

**Comment by zelig** [comment]
@obscuren No, I understood you. We can do it both ways: direct input is easier to implement, but with file paths you more actively discourage people from showing their key on screen or record in command history. was my point. so?

**Comment by zelig** [comment]
support for presale wallet import https://github.com/ethereum/go-ethereum/issues/267 needed too no?

**Comment by subtly** [comment]
Fewer options for users is better. File paths make importing an exported key easier and windows users don't deal much with stdin/stdout.
Ideally export will never be plaintext and decrypting would require a separate command. Import is great for testing whereas the only use-case for export is for users. Is there a reason export would need to be plaintext?

Just my thoughts. Whatever ya'll come up with, having it documented in -help or wiki would be great for system testing :)

**Comment by zelig** [comment]
@subtly thx 
wiki will be updated
https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts

**Comment by zelig** [comment]
all cover in #550 and #580
