### ISSUE TITLE
block synchronisation improvements 

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#563]
- [ ] fix them bloody counters already (sometimes it shows negative number, still after #702)
- [x] implement intermediate (bounded, ordered, hash indexed) pool cache for unrequested blocks
- [ ] replace misguided unrequested block error and just pool cache the blocks, keep record of too many unrequested, unused blocks - check performed at node cache purge
- [x] remove td update from add block, optional td not in eth protocol spec any more - clarify - instead use first peer's TD to update other peers TD 
- [x] remember not to relay a block back to where it came from - or see network simulation results and implement the propagation scheme
- [ ] randomized pow to be clarified - PoW ethash cache for multiple epochs for safe transition
https://github.com/ethereum/go-ethereum/commit/5b9a0e711800013a27be73cf963823b61e1ef727
- [x] support exemption from TDcheck by suspended/future blocks clarify VUL #604,  and https://github.com/ethereum/go-ethereum/commit/0d1a9ce64847775b19ab1f0bbb7b2cc7771e862a,  https://github.com/ethereum/go-ethereum/commit/f4af9e95c2b63ba261423cba0a9c05e37395123b
- [x] nil block. really? need more info -> investigate https://github.com/ethereum/go-ethereum/commit/218bfeb60e9a9e7f0874db18135e7ad633ff83f1#630 
- [x] fix deadlock - https://gist.github.com/obscuren/e18f821d63f3c362914e
- [x] panic on checkTD #645 - cannot reproduce - probably fixed 
- [x] glogify logging
- [ ] update https://github.com/ethereum/go-ethereum/wiki/Blockpool
- [ ]  crash when exiting w ^C during blockchain sync #672 https://github.com/ethereum/go-ethereum/issues/707

**Comment by zelig** [comment]
should not close yet

**Comment by obscuren** [comment]
That's GH auto-close because you referenced it with "closes"

**Comment by zelig** [comment]
new downloader makes this obsolete
