### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#6]
This issue serves as a temporarily to do list
- [x] Add MIT License
- [x] Improve overall testing
- [x] Add Travis to eth packages
- [x] Retrieving peer blocks
- [x] Get peers from connecting peers
- [x] Add a "addpeer" option to the dev console
- [ ] Support Tor
- [x] UPnP
- [ ] NAT-PMP
- [x] Fix miner
- [x] Fix uncles
- [x] Improve self connect detection
- [x] Add disconnection reasons to peers
- [ ] Document libraries
- [x] Add sync mechanism to trie. Trie shouldn't commit any changes unless requested. The trie would add an extra caching layer.
- [x] Get rid of RlpValue and move on to ethutil.Value
- [x] Chain iterator (or partial iterator) `NewIterator(options *IteratorOptions)`
- [ ] Get rid of the secp256k1 lib and implement my own

**Comment by wijittrapha** [comment]
I still not understand. But thank you.
