### ISSUE TITLE
a bunch of CLI improvements

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#639]
- [x] hex key import support https://github.com/ethereum/go-ethereum/issues/635 - fixed in #678
- [x] ~ home dir expansion #567 - fixed in #671
- [x] create path or error if logfile doesnt exist, now we are crashing. #679 backlogged  will switch to glog
- [x] new flag for NatSpec (default off? hmm im not sure) - fixed in https://github.com/ethereum/go-ethereum/pull/668 #486

**Comment by zelig** [comment]
all dealt with
