### ISSUE TITLE
bunch of CLI/JS admin related issues to check/fix

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#721]
- [x]  geth show "primary" account #732 
- [x] improve README Broken link for detailed go build instructions #661 fixed in #761
- [x]  Correct subdirectory used for keys and use os.Remove instead of RemoveAll #443 fixed in #796
- [x] ~~anything for filters and watch support~~ @frozeman @zsfelfoldi 
- [x] remove minGasPrice #754 fixed in #763
- [x] ~~RPC access control #745~~
- [x] implement stopRPC #729
- [x] rpccorsheader arg to startRPC
- [x]  admin.miner.start() hangs until the dag is generated
- [x] stop with fatal error if RPC or mining cannot start (many reported issues about hidden msgs)
- [x] ~~admin.unlock timeout issue #665~~
- [x]  ~~eth_defaultBlock #306 #310~~
- [x] confirm if there is string conversion issues, #710 
- [x]  ~~console "admin" feature to view pending transactions #675~~ 
- [x]  ubuntu address after new account #508 
- [x] reenable -shh option on command line #755
- [x] pprof via CLI + pprof port #755
- [x] update wiki with new functionality

**Comment by frozeman** [comment]
Also `admin.miner.start()` hangs for me until the dag is generated. ideally it returns true and let me do other stuff in the meanwhile. I thought somebody put an issue up for this already. So this might be somewhere around already and should be add to this list.

**Comment by zelig** [comment]
thx added
