### ISSUE TITLE
Ethash frontier update

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#757]
This issue collected all ethash related issues. @LefterisJP 
we need to make sure all these tick off before frontier.

* [x] integrate minerthreads in Ethereum.StartMining
* [x] pass minerthreads admin JS admin.miner.start 
* [x] pass minerthreads in CLI flag
* [ ] ? miner tests using the test mini-DAG
* [x] update CLI makedag subcommand to support generating DAG for any epoch
* [x] check blocktests running time and unskip them if ok

----

* [x] Move DAG file handling to ethash enhancement question #555 
* [x] ethash crashes on epoch when mining bug #705 
* [x] Eventer blocked by miner bug #697
* [x] Mining on private network & wrong DAG epoch #674 
* [x] Ethereum CLI - Windows - runtime: out of memory: cannot allocate 1073741824-byte block #562
* [x] fatal error: unexpected signal during runtime execution on Windows 64bit bug #524
* [x] SEC-24 Parent issue for ethash / PoW security issues vuln #499
* [x] Mining progress can possibly be stunted by determined attacker if difficulty gets high enough #274 
* [x] SIGABRT: abort during cgo execution #746

**Comment by LefterisJP** [comment]
I will help as much as I can, but golang is not my specialty. I am currently working on making the GO bridge use the new API. I will open a Pull Request and request feedback tomorrow probably.

**Comment by fjl** [comment]
The new bridge is almost done, see ethereum/ethash#41 for progress.

**Comment by Gustav-Simonsson** [comment]
Integration PR: https://github.com/ethereum/go-ethereum/pull/808

**Comment by Gustav-Simonsson** [comment]
Update: After debugging a bunch of bugs with @LefterisJP we now have a version where DAG creation works through Go bridge and mining works both on private chain and on testnet.  Will verify it for block tests as well (their startup needs some updates to work with current develop branch)

One issue we found is that this call: https://github.com/LefterisJP/ethash/blob/finalize_and_use_new_api/ethash.go#L79  causes the Go garbage collector to run https://github.com/LefterisJP/ethash/blob/finalize_and_use_new_api/ethash.go#L67  before the C function is done with building the DAG.

This results in the C code running into segfault when trying to reference the cache in https://github.com/LefterisJP/ethash/blob/finalize_and_use_new_api/src/libethash/internal.c#L93

Commenting out the finalizer call avoids deallocating the cache before DAG building is done.

We should find out why the Go runtime / GC considers this cache to be unreachable before this call returns: https://github.com/LefterisJP/ethash/blob/finalize_and_use_new_api/ethash.go#L169

**Comment by Gustav-Simonsson** [comment]
Edit: moving the finalizer until after the call also works and should have same intended behavior.

**Comment by Gustav-Simonsson** [comment]
Another update: @fjl suggested a better way to clear the cache by moving the finalizer call to getCache and explicitly free the temp cache in makeDAG

**Comment by obscuren** [comment]
All that's left to do is add miner control over the CPU's being used. It will require some significant re-write on the miner's part since it initialises the amount of agents on init.

**Comment by zelig** [comment]
now only 1 issue left, support miniDAG for testing. but this is not a frontier show stopper

**Comment by fjl** [comment]
You can do this now. Just use ethash.NewForTesting.

**Comment by zelig** [comment]
i know we can, we just dont yet :) but on second thought that shouldnt be an ethash issue any more. closing this ftw
