### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#758]
* [x] label unsupported RPC calls in Frontier #740 @frozeman @tgerring 
* [x] document "latest/pending" on `getBlock`
* [x] update cli options wiki #721 @zelig
* [x] console: document new debug methods @zelig
* [x] install pages @fjl
* [x] user guide - first timer tutorial @alexvandesande 
* [x] natspec/urlhint/cmd docs #486 @zelig 
* [x] write https://github.com/ethereum/go-ethereum/wiki/Contracts-and-Transactions 
* [x] GPU mining *must* be included at Frontier Launch #471
* [x] Liaise with comms - give them clear entry points - everybody should know where is the ultimate oracle to point to 

~~how to PR section to developer https://github.com/ethereum/go-ethereum/wiki/Developers%27-Guide @obscuren~~

**Comment by obscuren** [comment]
Re-open if more docs need to be added
